<?php


class ImageUpload extends DataObject
{
	public $__table = 'image_uploads';
	public $id;
	public $title;
	public $fullSizePath; //Stores the original file maximum width of 1068px
	public $generateMediumSize;
	public $mediumSizePath; //Stores the thumbnail with a maximum size of 350px
	public $generateSmallSize;
	public $smallSizePath; //Stores the thumbnail with a maximum size of 200x200px
	public $type;

	static $mediumSize = 350;
	static $smallSize = 200;
	static function getObjectStructure()
	{
		global $serverName;
		return [
			'id' => array('property' => 'id', 'type' => 'label', 'label' => 'Id', 'description' => 'The unique id within the database'),
			'title' => array('property' => 'title', 'type' => 'text', 'label' => 'Title', 'description' => 'The title of the image', 'size' => '40', 'maxLength'=>255),
			'type' => array('property' => 'type', 'type' => 'text', 'label' => 'Type', 'description' => 'The type of image being uploaded', 'maxLength' => 50),
			'fullSizePath' => array('property'=>'fullSizePath', 'type'=>'image', 'label'=>'Full Size Image', 'description'=>'The full size image (max width 1068px)', 'maxWidth' => 1068, 'maxHeight' => 1068, 'path' => '/data/aspen-discovery/' . $serverName . '/uploads/web_builder_image/full', 'displayUrl' => '/WebBuilder/ViewImage?size=full&id=', 'hideInLists' => true),
			'generateMediumSize' => array('property' => 'generateMediumSize', 'type' => 'checkbox', 'label' => 'Generate medium size image', 'default' => 1, 'hideInLists' => true),
			'mediumSizePath' => array('property'=>'mediumSizePath', 'type'=>'image', 'label'=>'Medium Size Image', 'description'=>'The medium size image (max width 350px)', 'maxWidth' => ImageUpload::$mediumSize, 'maxHeight' => ImageUpload::$mediumSize, 'path' => '/data/aspen-discovery/' . $serverName . '/uploads/web_builder_image/medium', 'displayUrl' => '/WebBuilder/ViewImage?size=medium&id=', 'hideInLists' => true),
			'generateSmallSize' => array('property' => 'generateSmallSize', 'type' => 'checkbox', 'label' => 'Generate small size image', 'default' => 1, 'hideInLists' => true),
			'smallSizePath' => array('property'=>'smallSizePath', 'type'=>'image', 'label'=>'Small Size Image', 'description'=>'The small size image (max width 200px)', 'maxWidth' => ImageUpload::$smallSize, 'maxHeight' => ImageUpload::$smallSize, 'path' => '/data/aspen-discovery/' . $serverName . '/uploads/web_builder_image/small', 'displayUrl' => '/WebBuilder/ViewImage?size=small&id='),
		];
	}

	function getDisplayUrl($property){
		if (empty($this->id)){
			return '';
		}
		if ($property == 'mediumSizePath'){
			$size = 'medium';
		}elseif ($property == 'smallSizePath'){
			$size = 'small';
		}else{
			$size = 'full';
		}
		return '/WebBuilder/ViewImage?size=' . $size . '&id=' . $this->id;
	}

	function insert()
	{
		$this->generateDerivatives();
		return parent::insert(); // TODO: Change the autogenerated stub
	}

	function update()
	{
		$this->generateDerivatives();
		return parent::update(); // TODO: Change the autogenerated stub
	}

	private function generateDerivatives()
	{
		if (!empty($this->fullSizePath)){
			global $serverName;
			require_once ROOT_DIR . '/sys/Covers/CoverImageUtils.php';
			$fullSizeFile = '/data/aspen-discovery/' . $serverName . '/uploads/web_builder_image/full/' . $this->fullSizePath;
			if ($this->generateMediumSize && empty($this->mediumSizePath)){
				$mediumFile = '/data/aspen-discovery/' . $serverName . '/uploads/web_builder_image/medium/';
				if (!file_exists($mediumFile)){
					mkdir($mediumFile, 0755, true);
				}
				$mediumFile .= $this->fullSizePath;
				if (resizeImage($fullSizeFile, $mediumFile, ImageUpload::$mediumSize, ImageUpload::$mediumSize)){
					$this->mediumSizePath = $this->fullSizePath;
				}
			}
			if ($this->generateSmallSize && empty($this->smallSizePath)){
				$smallFile = '/data/aspen-discovery/' . $serverName . '/uploads/web_builder_image/small/';
				if (!file_exists($smallFile)){
					mkdir($smallFile, 0755, true);
				}
				$smallFile .= $this->fullSizePath;
				if (resizeImage($fullSizeFile, $smallFile, ImageUpload::$smallSize, ImageUpload::$smallSize)){
					$this->smallSizePath = $this->fullSizePath;
				}
			}
		}
	}
}