<?php

/**
 * Description goes here
 *
 * @category Pika
 * @author Mark Noble <mark@marmot.org>
 * Date: 7/21/2016
 * Time: 4:05 PM
 */
class ClaimAuthorshipRequest extends DB_DataObject{
	public $__table = 'claim_authorship_requests';
	public $id;
	public $name;
	public $phone;
	public $email;
	public $message;
	public $pid;
	public $dateRequested;

	public static function getObjectStructure(){
		$structure = array(
				array('property'=>'name', 'type'=>'text', 'label'=>'Name', 'description'=>'Name', 'maxLength' => 100, 'required' => true),
				array('property'=>'phone', 'type'=>'text', 'label'=>'Phone', 'description'=>'Phone', 'maxLength' => 20, 'required' => true),
				array('property'=>'email', 'type'=>'email', 'label'=>'E-mail Address', 'description'=>'E-mail Address', 'maxLength' => 100, 'required' => true),
				array('property'=>'message', 'type'=>'text', 'label'=>'Additional Information', 'description'=>'Additional information about your request for authorship', 'maxLength' => 255, 'required' => false),
				'pid' => array('property'=>'pid', 'type'=>'hidden', 'label'=>'PID of Object', 'description'=>'ID of the object in ', 'maxLength' => 50, 'required' => true),
				'dateRequested' => array('property'=>'dateRequested', 'type'=>'hidden', 'label'=>'The date this request was made'),

		);
		return $structure;
	}

	public function insert() {
		$this->dateRequested = time();
		return parent::insert(); // TODO: Change the autogenerated stub
	}
}