package org.vufind;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

public class SearchAutocompleteTest extends TestTask{
	@Override
	public String getTestUrl() {
		int randomTerm = (int)Math.floor(Math.random() * terms.length);
		String term = terms[randomTerm];
		//Trim a random amount from the search term 
		if (term.length() > 4){
			int charsToTrim = (int)Math.floor(Math.random() * (term.length() - 4) );
			int endChar = term.length() - charsToTrim;
			//logger.info("Triming " + term + " to " + endChar + " charsToTrim= " + charsToTrim + " term.length()=" + term.length());
			term = term.substring(0, endChar);
		}
		//Url encode the term 
		try {
			term = URLEncoder.encode(term, "UTF-8");
		} catch (UnsupportedEncodingException e) {
			logger.error("Error encoding term " + term, e);
		}
		return this.baseUrl + "/Search/AJAX?method=GetAutoSuggestList&type=Keyword&searchTerm=" + term;
		
	}

	@Override
	public boolean validateTest(String pageContents) {
		if (pageContents.matches("(?si)\\[.*\\]")){
			return true;
		}else{
			logger.info("Failed validation contents were:'" + pageContents + "'");
		}
		return false;
	}
	
	@Override
	public boolean expectHTML() {
		return true;
	}

	@Override
	public boolean expectImage() {
		return false;
	}
	
	private String[] terms = new String[]{
		"ajgklu",
		"ceramics",
		"harry ptter",
		"harry potter",
		"o.a.r.",
		"cars",
		" hostile planet",
		" sign in & rate this title. legend of sleepy holl...",
		" sign in & rate this title. legend of sleepy holl...",
		"140271318",
		"alice springs",
		"andrew davis",
		"benefits of honey",
		"carpenters: gold - greatest hits",
		"catering",
		"catering buisness",
		"christopher hart",
		"churches in britain",
		"cut your energy bill",
		"d harkness",
		"data streams: models and algorithms",
		"egypt and their neighbors",
		"fear and loathing: on the campaign trail '72",
		"fence building",
		"fences",
		"first supreme court",
		"glee",
		"goapele",
		"gonzo republic: hunter s. thompson's america",
		"gregory c. randall",
		"harkness,deborah",
		"it application management",
		"itil",
		"joke books",
		"kissing hand",
		"marvin meyer",
		"mattie spencer",
		"mike markel (2009). technical communication (9th ...",
		"movies with woody allen",
		"movies woody allen",
		"sacramento, ca travel",
		"sum 41",
		"summer reading list",
		"the lost world",
		"the money thing",
		"water for elephants",
		"wildfire 7 the movie",
		"\" all about me books\"",
		"\"(on order)\"",
		"\"anxiety",
		"\"anxiety alternative treatment.\"",
		"\"audiobooks\"",
		"\"audiobooks.\"",
		"\"cave of forgotten dreams - chauvet cave\"",
		"\"chinese language materials\"",
		"\"chinese sound track",
		"\"comedy films.\"",
		"\"creative writing\"",
		"\"david & david\"",
		"*audio books*",
		"0 to 6 touchpoints",
		"0078186781 or 9780078186783",
		"0385517459",
		"0ctober sky",
		"10 secrets",
		"100",
		"100 thing",
		"100 thing challenge",
		"1000 blessings",
		"a women's world",
		"a writers reference",
		"a writers reference 6th edition by diana hacker",
		"a year and six seconds",
		"a-z",
		"aaron copeland",
		"abbe",
		"abbe pier",
		"abnormal psychology",
		"abs diet",
		"abuse",
		"academy awa",
		"alice's adventures in wonderland",
		"alice's adventures in wonderland lewis",
		"alicia keys",
		"alicia witt",
		"all about me",
		"all about me preschool books",
		"all clear speaking, listening, expressions",
		"all i wanna do",
		"all killer no filler  sum 41",
		"all killer no filler / sum 41",
		"all quiet on the western front",
		"all the pretty hearses",
		"all together dead",
		"allisonbrennan",
		"ally mcbeal",
		"almond flour co",
		"animals",
		"animation",
		"ann franke",
		"ann of green gables",
		"anna karina",
		"anne hathaway",
		"anne of gre gables",
		"anne of green gables",
		"annie",
		"annie dillard",
		"annie dillard, an american childhood",
		"anno's math games",
		"annotated alice",
		"another one bites the dust",
		"anthony robbins",
		"anti-inflammation diet and recipe books",
		"antique dolls",
		"antlr",
		"barbara rosenblat",
		"barbara stanwyck",
		"bare naked ladies",
		"barefoot books",
		"barenaked ladies",
		"barlowgirl",
		"barney's version",
		"barrons",
		"bart the bear",
		"baseball",
		"basements",
		"basketball",
		"bat man",
		"bats",
		"batteries not included",
		"broke",
		"bronte",
		"brothers & sisters dvd",
		"brothers soltau",
		"bruce springsteen",
		"bruce springsteen the river",
		"brue springsteen",
		"bruno mars",
		"buck",
		"buck schirner",
		"buck wheat",
		"buckaroo",
		"buick 1998 chiltons",
		"building a deck",
		"building an outdoor pizza oven",
		"building confidence",
		"cutting for stone",
		"d-pryde",
		"d5000",
		"d5100",
		"daddy & them",
		"daddy yankee",
		"daniel silva",
		"dantes inferno",
		"darcy and elizabeth",
		"darius rucker",
		"darrel odgers",
		"darren hardy",
		"darrius rucker",
		"darryl odgars",
		"dave mason",
		"dave matthews band",
		"dave robsaw",
		"david",
		"david & david",
		"david baldacci",
		"orm 2290",
		"format cd",
		"format cd, fiction, detective, mystery",
		"fortran",
		"foster children",
		"foster the people",
		"foundamentals of avionics",
		"framed",
		"france abc's",
		"francine rivers",
		"francisco pizarro",
		"frankie",
		"frankie goes to hollywood",
		"franklin and the duckling",
		"franklin and the magic show",
		"franklin and the stopwatch",
		"franklin fibs",
		"khloe and lamar",
		"kick abs pilates",
		"kidnapped masterpiece",
		"kids",
		"kids concoctions",
		"kids cook 123",
		"kids cookbook",
		"kids movie",
		"kids science ideas",
		"kill a watt",
		"kill alex cross",
		"kill me if you can, patterson",
		"kim karda",
		"kindle",
		"king edward viii",
		"king killer series",
		"kong fu",
		"korean movies",
		"krakatoa",
		"kris allen",
		"kt",
		"kt tunstal",
		"kt tunstell",
		"kuck ga da pu",
		"kundalini",
		"kyle hilton",
		"la",
		"la theatre works",
		"la vie en rose",
		"lady gaga",
		"ladybugs",
		"lambert miranda",
		"landscape design trellis",
		"landscape flower trellis",
		"emiotics",
		"sense of hearing",
		"sermons",
		"seuss",
		"seven habits of successful people",
		"sewing",
		"sex",
		"sex addiction",
		"sex and the city",
		"sex and the city dvd - season 6",
		"sex and the city season 6 part 1 dvd",
		"sex and the city season 6 part 2 dvd",
		"sexual",
		"shadow's lure",
		"shaggy dog 2006",
		"fish: a memoir of a boy in a man's prison\"",
		"\"ginsberg, allen,\"",
		"\"jim weiss\"",
		"\"kirsten ashley\"",
		"\"orloff, judith.\"",
		"\"peter wagner\"",
		"\"popular music\"",
		"\"richard shell\"",
		"\"self-confidence\"",
		"'dylan ratigan'",
		"'john sanford'",
		"'kathy reichs'",
		"'kent haruf'",
		"'peter sheahan'",
		"'sanford'",
		"((sederas or federals)",
		"(armegedeon or armageddon)",
		"(armegedon or armageddon)",
		"ace atkins",
		"ace collins",
		"acid reflux",
		"acosta, oscar",
		"across the years",
		"acuff",
		"acupressure",
		"adam ant",
		"adam bertram",
		"adam curtis",
		"adam hartung",
	};
}
