[php-fpm]
user = www-data
group = www-data
listen = 0.0.0.0:{phpFpmPort}
listen.owner = www-data
listen.group = www-data


; Process manager settings
pm = dynamic
pm.max_children = 6
pm.start_servers = 2
pm.min_spare_servers = 2
pm.max_spare_servers = 5
chdir = /usr/local/aspen-discovery/code/web


; Kill long-running requests after 300s
request_terminate_timeout = 300


; Logging (stdout/stderr for Docker)
access.log = /proc/self/fd/2
catch_workers_output = yes
decorate_workers_output = yes
php_flag[log_errors] = on
php_admin_value[error_log] = /proc/self/fd/2


; Session Settings
php_admin_value[session.use_cookies] = 1
php_admin_value[session.use_only_cookies] = 1
php_admin_value[session.auto_start] = 0
; php_admin_value[session.cookie_secure] = 1
php_admin_value[session.cookie_lifetime] = 0
php_admin_value[session.gc_maxlifetime] = 6000


; Uncomment these lines if you want to show all errors
; php_admin_value[display_errors] = 1
; php_admin_value[error_reporting] = 2047


; Memory Settings
php_admin_value[memory_limit] = 512M
php_admin_value[max_execution_time] = 300
php_admin_value[default_socket_timeout] = 300
