Alias "/fonts" "/data/aspen-discovery/aspen.localhost/fonts"
<Directory /data/aspen-discovery/aspen.localhost/fonts>
	Require all granted
</Directory>

Alias "/images" "/data/aspen-discovery/aspen.localhost/images"
<Directory /data/aspen-discovery/aspen.localhost/images>
	Require all granted
</Directory>

Alias "/files" "/data/aspen-discovery/aspen.localhost/files"
<Directory /data/aspen-discovery/aspen.localhost/files>
	Require all granted
</Directory>