networks:
  net-aspen:

volumes:
  solr:

services:
  backend:
    image: ${BACKEND_IMAGE_TAG:-aspendiscovery/aspen}
    env_file:
      - .env
    networks:
      - net-aspen
    tty: true
    volumes:
      - ${ASPEN_HOME:-./aspen}/conf:/usr/local/aspen-discovery/sites/${SITE_NAME}
      - ${ASPEN_HOME:-./aspen}/data:/data/aspen-discovery/${SITE_NAME}
      - ${ASPEN_HOME:-./aspen}/logs:/var/log/aspen-discovery/${SITE_NAME}
    depends_on:
      db:
        condition: service_healthy

  apache:
    image: ${BACKEND_IMAGE_TAG:-aspendiscovery/aspen}
    env_file:
      - .env
    ports:
      - "85:80"
    networks:
      - net-aspen
    volumes:
      - ${ASPEN_HOME:-./aspen}/conf:/usr/local/aspen-discovery/sites/${SITE_NAME}
      - ${ASPEN_HOME:-./aspen}/data:/data/aspen-discovery/${SITE_NAME}
      - ${ASPEN_HOME:-./aspen}/logs:/var/log/aspen-discovery/${SITE_NAME}
    command:
      - apache
    depends_on:
      - backend
    tty: true

  cron:
    image: ${BACKEND_IMAGE_TAG:-aspendiscovery/aspen}
    env_file:
      - .env
    networks:
      net-aspen:
        aliases:
          - ${SITE_NAME}
    tty: true
    volumes:
      - ${ASPEN_HOME:-./aspen}/conf:/usr/local/aspen-discovery/sites/${SITE_NAME}
      - ${ASPEN_HOME:-./aspen}/data:/data/aspen-discovery/${SITE_NAME}
      - ${ASPEN_HOME:-./aspen}/logs:/var/log/aspen-discovery/${SITE_NAME}
    command:
      - cron
    depends_on:
      - backend
      - apache


  db:
    image: ${MARIADB_IMAGE:-mariadb:10.5}
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:-password}
      - MARIADB_USER=${DATABASE_USER:-user123}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD:-passwd}
      - MARIADB_DATABASE=${DATABASE_NAME:-aspen}
    volumes:
      - ${ASPEN_HOME:-./aspen}/database:/var/lib/mysql
    networks:
      - net-aspen
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 10

  solr:
    image: ${SOLR_IMAGE_TAG:-aspendiscovery/solr}
    env_file:
      - .env
    environment:
      - SOLR_PORT=${SOLR_PORT:-8983}
    ports:
      - "${SOLR_PORT}:${SOLR_PORT:-8983}"
    volumes:
      - solr:/var/solr
    networks:
      - net-aspen
    entrypoint:
    - /bin/bash
    - '-c'
    - |
      init-var-solr
      # Series core
      precreate-core series /opt/solr/server/solr/configsets/series
      cp -r /opt/solr/server/solr/configsets/series/* series

      # Genealogy core
      precreate-core genealogy /opt/solr/server/solr/configsets/genealogy
      cp -r /opt/solr/server/solr/configsets/genealogy/* genealogy

      # Grouped Works v2 core
      precreate-core grouped_works_v2 /opt/solr/server/solr/configsets/grouped_works_v2
      cp -r /opt/solr/server/solr/configsets/grouped_works_v2/* grouped_works_v2

      # Lists core
      precreate-core lists /opt/solr/server/solr/configsets/lists
      cp -r /opt/solr/server/solr/configsets/lists/* lists

      # Course Reserves core
      precreate-core course_reserves /opt/solr/server/solr/configsets/course_reserves
      cp -r /opt/solr/server/solr/configsets/course_reserves/* course_reserves

      # Open Archives core
      precreate-core open_archives /opt/solr/server/solr/configsets/open_archives
      cp -r /opt/solr/server/solr/configsets/open_archives/* open_archives

      # Website Pages core
      precreate-core website_pages /opt/solr/server/solr/configsets/website_pages
      cp -r /opt/solr/server/solr/configsets/website_pages/* website_pages

      # Events core
      precreate-core events /opt/solr/server/solr/configsets/events
      cp -r /opt/solr/server/solr/configsets/events/* events


      chown -R solr:solr /var/solr
      runuser -u solr -- solr-foreground
