<?php
require_once ROOT_DIR . '/services/MyAccount/MyAccount.php';

class MyAccount_AccountRenewal extends MyAccount {
	function launch(): void {
		global $interface;

		$user = UserAccount::getLoggedInUser();
		if (empty($user) || !$user) {
			$this->display('accountRenewal.tpl', 'Renew Your Account');
			$interface->assign('loggedIn', false);
			return;
		}

		$ilsName = $user->getILSName();
		// The present version only supports Koha, but is written in such a way that enabling support for ILS can be done as future enhancements
		if ($ilsName !== 'koha') {
			$this->display('accountRenewal.tpl', 'Renew Your Account');
			$interface->assign('ilsUnsupported', true);
			return;
		}

		$sessionKey = 'account_renewal_data_' . $user->id;
		$renewalInfo = $this->getRenewalInformation($sessionKey, $user->unique_ils_id);
		
		$userAgreementVerificationMessage = $renewalInfo['data']['self_renewal_settings']['self_renewal_information_message'] ?? '';
		$selfRenewalSettings = $renewalInfo['data']['self_renewal_settings'] ?? [];
		$hasVerificationCheck = !empty($userAgreementVerificationMessage);

		$currentStepName = $_POST['currentStep'] ?? $_GET['currentStep'] ?? 'start'; 
		$requestedDirection = $_POST['navigation'] ?? 'reload';

		$validationError = '';
		$currentWarningMessage = '';

		$userAgreementResponse = $_POST['userAgrees'] ?? '';

		// handle user responses to the verification check step
		if ($currentStepName === 'verification_check') {
			$userAgreementCheckOutcome = $this->checkUserAgreement($userAgreementResponse);
			if (isset($userAgreementCheckOutcome['message'])) {
				if ($userAgreementResponse === 'no') {
					$currentWarningMessage = $userAgreementCheckOutcome['message'];
				} else {
					$validationError = $userAgreementCheckOutcome['message'];
				}
			}
		}

		// override currentStep with the next as we prepare to relaunch
		$direction = $this->getDirection($currentStepName, $requestedDirection, $userAgreementCheckOutcome['userAgrees'] ?? false);
		$nextStepName = $this->getNextStep($direction, $currentStepName, $hasVerificationCheck);
		$nextStep = $this->getCurrentStepData($nextStepName, $userAgreementVerificationMessage);

		// generate the contact information form for use
		if ($nextStepName === 'verifyContactInformation') {
			$interface->assign('canSave', false);
			$interface->assign('canUpdateContactInfo', false);
			$contactInfoData = $this->getContactInformationData($ilsName);

			// this is so that the form generated by the Koha driver can be used withing the account renewal form
			if (isset($contactInfoData['patronUpdateForm'])) {
				$contactInfoData['patronUpdateForm'] = preg_replace('/<form[^>]*>/i', '', $contactInfoData['patronUpdateForm']);
				$contactInfoData['patronUpdateForm'] = str_ireplace('</form>', '', $contactInfoData['patronUpdateForm']);
			}
			foreach ($contactInfoData as $key => $value) {
				$interface->assign($key, $value);
			}
			$interface->assign('edit', true);
		}

		$interface->assign('currentStep', $nextStep);
		$interface->assign('selfRenewalSettings', $selfRenewalSettings);
		$interface->assign('hasVerificationCheck', $hasVerificationCheck);
		$interface->assign('ilsUnsupported', false);
		$interface->assign('validationError', $validationError);
		$interface->assign('currentWarningMessage', $currentWarningMessage);
		$interface->assign('userAgrees', $userAgreementCheckOutcome['userAgrees'] ?? '');

		$this->display('accountRenewal.tpl', 'Renew Your Account');
	}

	private function checkUserAgreement(string $userAgrees): array {
		$result = [
			'userAgrees' => false,
			'message' => 'Please select Yes or No to proceed.',
		];

		if ($userAgrees === 'yes') {
			$result['userAgrees'] = true;
			$result['message'] = '';
			return $result;
		}

		if ($userAgrees === 'no') {
			$result['message'] = 'You chose not to proceed with this verification. Please review the information.';
			return $result;
		} 
		
		return $result;
	}

	private function getContactInformationData(string $ilsName): array {
		$data = [];

		$user = UserAccount::getLoggedInUser();

		$patronUpdateForm = $user->getPatronUpdateForm();
		if ($patronUpdateForm != null) {
			$data['patronUpdateForm'] = $patronUpdateForm;
		} else {
			$user->loadContactInformation();
		}

		$data['profile'] = $user;

		$patronHomeLibrary = $user->getHomeLibrary(true);

		$canUpdateContactInfo = false;
		$canUpdateAddress = false;
		$canUpdatePhoneNumber = false;
		$canUpdateWorkPhoneNumber = false;
		$showWorkPhoneInProfile = false;
		$showCellphoneInProfile = false;
		$showNoticeTypeInProfile = false;
		$allowPinReset = false;
		$showAlternateLibraryOptionsInProfile = false;
		$allowAccountLinking = true;
		$passwordLabel = 'Library Card Number';

		if ($patronHomeLibrary != null) {
			$canUpdateContactInfo = ($patronHomeLibrary->allowProfileUpdates == 1);
			$canUpdateAddress = ($patronHomeLibrary->allowPatronAddressUpdates == 1);
			$canUpdatePhoneNumber = ($patronHomeLibrary->allowPatronPhoneNumberUpdates == 1);
			$showWorkPhoneInProfile = ($patronHomeLibrary->showWorkPhoneInProfile == 1);
			$showCellphoneInProfile = ($patronHomeLibrary->showCellphoneInProfile == 1);
			$canUpdateWorkPhoneNumber = ($patronHomeLibrary->allowPatronWorkPhoneNumberUpdates == 1);
			$showNoticeTypeInProfile = ($patronHomeLibrary->showNoticeTypeInProfile == 1);
			$allowPinReset = ($patronHomeLibrary->allowPinReset == 1);
			$showAlternateLibraryOptionsInProfile = ($patronHomeLibrary->showAlternateLibraryOptionsInProfile == 1);
			$allowAccountLinking = ($patronHomeLibrary->allowLinkedAccounts == 1);
			$passwordLabel = str_replace('Your', '', $patronHomeLibrary->loginFormPasswordLabel ? $patronHomeLibrary->loginFormPasswordLabel : 'Library Card Number');

			if (($user->_finesVal > $patronHomeLibrary->maxFinesToAllowAccountUpdates) && ($patronHomeLibrary->maxFinesToAllowAccountUpdates > 0)) {
				$canUpdateContactInfo = false;
				$canUpdateAddress = false;
			}
		}

		$data['canUpdateContactInfo'] = $canUpdateContactInfo;
		$data['canUpdateAddress'] = $canUpdateAddress;
		$data['canUpdatePhoneNumber'] = $canUpdatePhoneNumber;
		$data['canUpdateWorkPhoneNumber'] = $canUpdateWorkPhoneNumber;
		$data['showWorkPhoneInProfile'] = $showWorkPhoneInProfile;
		$data['showCellphoneInProfile'] = $showCellphoneInProfile;
		$data['showNoticeTypeInProfile'] = $showNoticeTypeInProfile;
		$data['allowPinReset'] = $allowPinReset;
		$data['showAlternateLibraryOptions'] = $showAlternateLibraryOptionsInProfile;
		$data['allowAccountLinking'] = $allowAccountLinking;
		$data['passwordLabel'] = $passwordLabel;
		$data['showPreferredNameInProfile'] = $user->showPreferredNameInProfile();
		$data['allowUpdatesOfPreferredName'] = $user->allowUpdatesOfPreferredName();
		$data['pickupLocations'] = $user->getValidPickupBranches($user->getAccountProfile()->recordSource);
		$data['isHorizon'] = ($ilsName == 'horizon');
		$data['isCarlX'] = ($ilsName == 'carlx');
		$data['isSymphony'] = ($ilsName == 'symphony');
		$data['millenniumNoAddress'] = $canUpdateContactInfo && !$canUpdateAddress && in_array($ilsName, ['millennium', 'sierra']);
		$data['barcodePin'] = true;
		$data['offline'] = false;
		$data['allowHomeLibraryUpdates'] = false;
		$data['libraryName'] = '';

		return $data;
	}

	private function getCurrentStepData(string $currentStepName, string $userAgreementVerificationMessage): array {
		$data = [
			'name' => $currentStepName,
			'title' => '',
			'description' => ''
		];

		if ($currentStepName === 'start') {
			$data['title'] = 'Start';
			$data['description'] = 'Welcome to the account renewal process. Please click Continue to begin.';
		} elseif ($currentStepName === 'verification_check') {
			$data['title'] = 'Verification Questions';
			$data['description'] = $userAgreementVerificationMessage;
		} elseif ($currentStepName === 'verifyContactInformation') {
			$data['title'] = 'Confirm Contact Information';
			$data['description'] = 'Please review and update your contact information as needed.';
		} elseif ($currentStepName === 'done') {
			$data['title'] = 'Request Submitted.';
			$data['description'] = 'Your request has been processed.';
		} else {
			$data['title'] = 'Error';
			$data['description'] = 'An unexpected error occurred.';
		}

		return $data;
	}

	private function getDirection(string $currentStepName, string $requestedDirection, bool $userAgrees = false): string {
		if ($requestedDirection === 'back') {
			return 'back';
		}
		if ($requestedDirection === 'next' || $requestedDirection === 'continue') {
			if ($currentStepName === 'verification_check' && !$userAgrees) {
				return 'stay';
			}
			return 'next';
		}
		return 'stay';
	}

	private function getNextStep(string $direction, string $currentStepName, bool $hasVerificationCheck): string {
		if ($direction === 'stay') {
			return $currentStepName;
		}

		if ($currentStepName === 'start') {
			if ($direction === 'next') {
				return $hasVerificationCheck ? 'verification_check' : 'verifyContactInformation';
			}
			return 'start';
		}

		if ($currentStepName === 'verification_check') {
			return $direction === 'next' ? 'verifyContactInformation' : 'start';
		}

		if ($currentStepName === 'verifyContactInformation') {
			return $direction === 'next' ? 'done' : ($hasVerificationCheck ? 'verification_check' : 'start');
		}

		return $currentStepName;
	}

	private function getRenewalInformation(string $sessionKey, string $userIlsId): array {
		if (session_status() == PHP_SESSION_NONE) {
			session_start();
		}

		if (isset($_SESSION[$sessionKey])) {
			return $_SESSION[$sessionKey];
		}

		$ilsDriver = CatalogFactory::getCatalogConnectionInstance();

		$renewalInfo = $ilsDriver->getAccountRenewalInformationForPatron($userIlsId);
		$_SESSION[$sessionKey] = $renewalInfo;

		return $renewalInfo;
	}

	function getBreadcrumbs(): array {
		$breadcrumbs = [];
		$breadcrumbs[] = new Breadcrumb('/MyAccount/Home', 'Your Account');
		$breadcrumbs[] = new Breadcrumb('', 'Renew Your Account');
		return $breadcrumbs;
	}
}
