<?php


class GroupedWorkDisplayInfo extends DataObject {
	public $__table = 'grouped_work_display_info';
	public $id;
	public $permanent_id;
	public $title;
	public $author;
	public $seriesName;
	public $seriesDisplayOrder;
	public $addedBy;
	public $dateAdded;

	public function insert() {
		if (empty($this->seriesDisplayOrder)) {
			$this->seriesDisplayOrder = 0;
		}
		return parent::insert(); // TODO: Change the autogenerated stub
	}

	public function update() {
		if (empty($this->seriesDisplayOrder)) {
			$this->seriesDisplayOrder = 0;
		}
		return parent::update(); // TODO: Change the autogenerated stub
	}
}