<?php
	require_once ROOT_DIR . '/sys/ECommerce/Pay360Setting.php';
	require_once ROOT_DIR . '/sys/Account/UserPayment.php';

// Interacts with the Pay360 API
class Pay360_Client  {
	// class parameters
	public $catalogDriver;
	public $selectedFines;
	public $payment;
	
	// query generation
	private $_pay360Settings;
	private $_soapClient;
	private $_digest;

	// query responses
	public $invokeResponse;
	public $queryResponse;

	public function __construct($settingsId, $paymentId, $selectedFines = [], $catalogDriver = null, $setTimestamp = false, $payment = null) {
		$this->setSettings($settingsId);
		$this->setPayment($paymentId, $payment);

		$this->catalogDriver = $catalogDriver;
		$this->selectedFines = $selectedFines;

		if ($setTimestamp) {
			$this->setTimeStamp();
		}

		$this->setSoapClient();
		$this->_setDigest();
	}

	public function completeFineInIls(): bool {
		$patron = new User;
		$patron->id = $this->payment->userId;
		if(!$patron->find(true)) {
			return false;
		}
		$result = $patron->completeFinePayment($this->payment);
		return $result['success'];
	}

	public function setSettings($settingsId): void {
		$this->_pay360Settings = new Pay360Setting();
		$this->_pay360Settings->id = $settingsId;
		$this->_pay360Settings->find(true);
	}

	public function isPay360PollingEnabled(): bool {
		if (empty($this->_pay360Settings)) {
			return false;
		}
		return $this->_pay360Settings->pollingEnabled;
	}

	public function setPayment($paymentId, $payment = null): void {
		if ($payment) {
			$this->payment = $payment;
			return;
		}
		$this->payment = new UserPayment();
		$this->payment->id = $paymentId;
		$this->payment->find(true);
	}

	public function getOrderStatus($refresh = false) {
		$result = ['state' => 'COULD NOT FETCH'];
		if (!$refresh) {
			$result['state'] = $this->queryResponse->transactionState;
			if (isset($this->queryResponse->paymentResult)) {
				$result['status'] = $this->queryResponse->paymentResult->status;
			}
			return $result;
		}
		$this->_getQueryResponse();
		$result = ['state' => $this->queryResponse->transactionState];
		if (isset($this->queryResponse->paymentResult)) {
			$result['status'] = $this->queryResponse->paymentResult->status;
		}
		return $result;
	}

	public function setSoapClient() {
		$this->_soapClient = new SoapClient($this->_pay360Settings->wsdlUrl, ['features' => SOAP_SINGLE_ELEMENT_ARRAYS]);
	}
	
	public function setTimeStamp() {
		$this->payment->pay360Timestamp = gmdate("YmdHis");
	}

	public function createOrder(): bool {
		if (empty($this->_pay360Settings)) {
			return false;
		}

		$this->_getInvokeResponse();

		if (empty($this->invokeResponse)) {
			$this->payment->cancelled = true;
			$this->payment->error = true;
			$this->payment->message = "failed to connect to Pay360";
			$this->payment->update(); 
			return false;
		}

		if ($this->invokeResponse->transactionState  !== "IN_PROGRESS") {
			$this->payment->cancelled = true;
			$this->payment->error = true;
			$this->payment->orderId = $this->invokeResponse->scpReference;
			$this->payment->message = "failed invoke request for scpReference " .  $this->invokeResponse->scpReference . "failed with status " . $this->invokeResponse->invokeResult->status;
			$this->payment->update(); 
			return false;
		}

		$this->payment->pay360TransactionStateMessage = translate([
				'text' => 'This payment is still in progress. Check back later for an update.',
				'isPublicFacing' => true
			]);
		$this->payment->orderId = $this->invokeResponse->scpReference;
		$this->payment->update();
		return true;
	}

	public function handleOutcome(array $transactionStatus = [], $attempted = true): bool|null {
		if (!$attempted) {
			$this->payment->cancelled = true;
			$this->payment->message = 'Patron did not attempt the payment and back out of the process.';
			$this->payment->pay360TransactionStateMessage = 'This payment was not attempted.';
			$this->payment->update();
			return false;
		}
		
		if (empty($transactionStatus)) {
			$transactionStatus = [
				'state' => $this->queryResponse->transactionState,
				'status' => null
			];
			if (!empty($this->queryResponse->paymentResult)) {
				$transactionStatus['status'] = $this->queryResponse->paymentResult->status;
			}
		}

		// this state value is generated by Aspen for transactions where fetching from pay360 fails
		if($transactionStatus['state'] === 'COULD NOT FETCH') {
			$this->payment->cancelled = true;
			$this->payment->error = true;
			$this->payment->message = 'Transaction not found - could not fetch from Pay360.';
			$this->payment->pay360TransactionStateMessage = 'Transaction could not be retrieved.';
			$this->payment->update();
			return false;
		}

		if ($transactionStatus['state'] === 'INVALID_REFERENCE') {
			$this->payment->cancelled = true;
			$this->payment->error = true;
			$this->payment->message = 'Transaction not found - invalid reference.';
			$this->payment->pay360TransactionStateMessage = 'Transaction could not be retrieved.';
			$this->payment->update();
			return false;
		}

		if ($transactionStatus['state'] === 'IN_PROGRESS') {
			// do nothing, the polling process will be on-going
			return null;
		}

		if ($transactionStatus['state'] === 'COMPLETE') {
			
			if ($transactionStatus['status'] === 'SUCCESS') {
				$this->payment->message = 'This payment was successful.';
				$this->payment->pay360TransactionStateMessage = 'Payment successful.';
				if (!$this->completeFineInIls()) {
					$this->payment->error = true;
					$this->payment->message = 'Payment was received by Pay360 but could not be applied in the ILS. Please contact your library.';
					$this->payment->pay360TransactionStateMessage = 'Payment received but ILS update failed.';
				}
				$this->payment->update();
				return false;
			}

			if ($transactionStatus['status'] === 'CANCELLED') {
				$this->payment->cancelled = true;
				$this->payment->message = 'cancelled by patron. error id: '  . $this->queryResponse->paymentResult->errorDetails->errorId . ', error message: ' . $this->queryResponse->paymentResult->errorDetails->errorMessage;
				$this->payment->pay360TransactionStateMessage = 'Transaction attempt was cancelled.';
				$this->payment->update();
				return false;
			}

			if ($transactionStatus['status'] === 'CARD_DETAILS_REJECTED') {
				$this->payment->cancelled = true;
				$this->payment->message = 'card details rejected. error id: '  . $this->queryResponse->paymentResult->errorDetails->errorId . ', error message: ' . $this->queryResponse->paymentResult->errorDetails->errorMessage;
				$this->payment->pay360TransactionStateMessage = 'This payment failed - card details were rejected.';
				$this->payment->update();
				return false;
			}

			if ($transactionStatus['status'] === 'LOGGED_OUT') {
				$this->payment->cancelled = true;
				$this->payment->message = 'patron logged out. error id: '  . $this->queryResponse->paymentResult->errorDetails->errorId . ', error message: ' . $this->queryResponse->paymentResult->errorDetails->errorMessage;
				$this->payment->pay360TransactionStateMessage ='This payment failed - user logged out.';
				$this->payment->update();
				return false;
			}

			if ($transactionStatus['status'] === 'NOT_ATTEMPTED') {
				$this->payment->cancelled = true;
				$this->payment->message = 'patron did not attempt payment. error id: '  . $this->queryResponse->paymentResult->errorDetails->errorId . ', error message: ' . $this->queryResponse->paymentResult->errorDetails->errorMessage;
				$this->payment->pay360TransactionStateMessage = 'This payment was interrupted by the user.';
				$this->payment->update();
				return false;
			}

			if ($transactionStatus['status'] === 'ERROR') {
				$this->payment->error = true;
				$this->payment->cancelled = true;
				$this->payment->message = 'error: ' . $this->queryResponse->paymentResult->errorDetails->errorId . ': ' . $this->queryResponse->paymentResult->errorDetails->errorMessage;
				$this->payment->pay360TransactionStateMessage = 'This payment failed due to a third party error. Contact your library.';
				$this->payment->update();
				return false;
			}

			return false;
		}
		return false;
	}

	// API queries
	private function _getInvokeResponse(): void {
		if (empty($this->_soapClient) || empty($this->_pay360Settings) || empty($this->payment)) {
			return;  
		}

		$params = $this->_getInvokeParameters();
		$params['sale']['items']['item'] = $this->_getMultiLineItemParameters();
		
		try {
			$response = $this->_soapClient->scpSimpleInvoke($params);
		} catch (Exception $e) {
			$this->payment->error = true;
			$this->payment->message = $e->getMessage();
			$this->payment->update();
			return;
		}
		$this->invokeResponse = $response;
	}

	private function _getQueryResponse(): void {
		if (empty($this->_soapClient) || empty($this->_pay360Settings) || empty($this->payment)) {
			return;  
		}
		
		$params = [
			'credentials' => $this->_getCredentialParams(),
			'siteId' => $this->_pay360Settings->siteId,
			'scpReference' => $this->payment->orderId,
		];
		
		try {
			$response = $this->_soapClient->scpSimpleQuery($params);
		} catch (Exception $e) {
			return;
		}
		$this->queryResponse = $response;
	}

	// services
	private function _getMultiLineItemParameters(): array|null {
		if (!$this->catalogDriver) {
			return null;
		}
		$items = [];
		foreach( $this->selectedFines as $fine) {	
			$fineDetails = $this->catalogDriver->hasAdditionalFineFields() ? $this->catalogDriver->getFineById($fine['id'], true) : $fine;
			$amountInMinorUnits = $this->getMinorUnitsAmount($fineDetails['amountVal']);
			$item = [
				'itemSummary' =>[
					'description' => $fineDetails['reason'],
					'amountInMinorUnits' => $amountInMinorUnits,
					'displayableReference' => $fineDetails['reason'], 
				],
				'IgItemDetails' => [
					'additionalReference' => $fineDetails['reason'],
					'narrative' => $fineDetails['reason'],
					'customerInfo' => $fineDetails['message'],
				],
				'lineId' => $fineDetails['fineId']
			];
			if (isset($fineDetails['vatCode'])) {
				$item['tax'] = $fineDetails['vatCode'];
			}
			if (isset($fineDetails['fundCode'])) {
				$item['IgItemDetails']['fundCode'] = $fineDetails['fundCode'];
			}
			if (isset($fineDetails['reference'])) {
				$item['itemSummary']['reference'] = $fineDetails['reference'];
			}
			array_push($items, $item);
		}
		return $items;
	}

	private function _getInvokeParameters(): array| null {
		if (!$this->_digest || empty($this->_pay360Settings) || !$this->payment->pay360Timestamp) {
			return null;  
		}

		global $configArray;
		$amountInMinorUnits = $this->getMinorUnitsAmount($this->payment->totalPaid);

		$returnUrl = $configArray['Site']['url'] . "/MyAccount/AJAX?method=completePay360Order&paymentId=" . $this->payment->id ."&settingsId=" . $this->_pay360Settings->id;
		$backUrl = $configArray['Site']['url'] . "/MyAccount/AJAX?method=handlePay360OrderNotAttempted&paymentId=" . $this->payment->id ."&settingsId=" . $this->_pay360Settings->id;

		$parameters = [
			'credentials' => $this->_getCredentialParams(),
			'requestType' => 'payOnly',
			'requestId' => 'TEST',
			'routing' => [
				'returnUrl' => new SoapVar($returnUrl, XSD_STRING),
				'backUrl' => new SoapVar($backUrl, XSD_STRING),
				'siteId' => $this->_pay360Settings->siteId,
				'scpId' => $this->_pay360Settings->scpId,
			],
			'panEntryMethod' => 'ECOM',
			'sale' => [
				'saleSummary' => [
					'description' => "Aspen Discovery - Pay360 integration " .  $this->payment->id,
					'amountInMinorUnits' => $amountInMinorUnits,
				],
			],  
		];
		
		$patron = new User;
		$patron->id = $this->payment->userId;
		if(!$patron->find(true)) {
			return $parameters;
		}

		// pre-populate the cardholder billing information form
		$parameters['billing'] = [
			'cardHolderDetails' => [
				'cardHolderName' => $patron->firstname . ' ' . $patron->lastname,
			],
		];
		
		if($patron->email) {
			$parameters['billing']['cardHolderDetails']['contact'] = ['email' => $patron->email];
		}
		
		return $parameters;
	}

	private function _getCredentialParams(): array|null {
		if (!$this->_digest || empty($this->_pay360Settings) || !$this->payment->pay360Timestamp) {
			return null;  
		}
		return 	[
			'subject' => [
				'subjectType' => $this->_pay360Settings->subjectType,
				'identifier' => $this->_pay360Settings->scpId,
				'systemCode' => $this->_pay360Settings->systemCode,
			],
			'requestIdentification' => [
				'uniqueReference' => $this->payment->id,
				'timeStamp' => $this->payment->pay360Timestamp,
			],
			'signature' => [
				'algorithm' => $this->_pay360Settings->algorithm,
				'hmacKeyID' => $this->_pay360Settings->hmacKeyId,
				'digest' => $this->_digest,
			],
		];
	}

	private function _setDigest(): void {
		if ($this->_digest || empty($this->_pay360Settings) || !$this->payment->pay360Timestamp || empty($this->payment)) {
			return;  
		}
		$credentialsStr = $this->_pay360Settings->subjectType . "!" . $this->_pay360Settings->scpId . "!" . $this->payment->id . "!" . $this->payment->pay360Timestamp . "!" . $this->_pay360Settings->algorithm . "!" . $this->_pay360Settings->hmacKeyId;
		$hash = hash_hmac('sha256', $credentialsStr, base64_decode($this->_pay360Settings->privateKey), true);
		$this->_digest = base64_encode($hash);
	}

	private function getMinorUnitsAmount(string $totalAmount): string {
		$amount = (float)$totalAmount;
		$amountInMinorUnits = (int)round($amount * 100);
		return (string)$amountInMinorUnits;
	}
}